# `numpy
- core package for numerical computing in Python
- many packages built on top of numpy
- `numpy` optimized for processing, makes efficient use of memory, moreso than base Python and works more quickly

In [1]:
import numpy as np

# Variables
Think about variables as a name we assign to a particular object in Python

In [2]:
# assign a small array to a variable
a = np.array( [ [1,1,2], [3,5,8] ] )

When we run the cell, the variable and its value is stored. You can see the value in two ways:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## naming variables
We're going to use `snake_case` for naming variables. All lowercase, underscores to separate them

## variables and objects

**object**: object is a bundle of properties and actions about something specific.

Example:

- object: data frame
- properties: number of rows, names of columns, date created
- actions: selection a row, adding a column

Variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:

- The Sun = object
- sol = Spanish word for Sun = variable
- soleil = french for Sun = variable

In practice: we will use object and variable interchangeably. 

# Types

Each object in Python has a type.

type = what kind of object it is

Type is also the **class** of the object

We can see the type/class of an object by using the `type` function

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in `numpy`. We can check the type of an entry in the array by indexing:

In [6]:
print(a[0,0]) # indexing goes rows, columns
type(a[0,0])

1


numpy.int64

In [7]:
# how to access value 5 in the array
print(a[1,1])

5


# Functions

`print` is our first example of a Python function

A function:
- takes a set of **arguments** separated by commas
- takes those arguments to produce an **output**

argument is also called **parameter**

We can ask information about a function by executing `?` followed by function name

In [8]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


Contains:
- first line: function showing all of its arguments in ()
- short description of what the function does
- list of the arguments and a brief explanation of each

Different types of arguments inside the parentheses. there are two types:

- **non-optional**: arguments you need to specify for the function to do something
- **optional**: arguments pre-filled with a value, but we can override them. Optional arguments appear inside the parentheses as 

`optional argument = default_value`

In [12]:
print('changing the \ndefault end argument', end=':)')

changing the 
default end argument:)