# `numpy
- core package for numerical computing in Python
- many packages built on top of numpy
- `numpy` optimized for processing, makes efficient use of memory, moreso than base Python and works more quickly

In [1]:
import numpy as np

# Variables
Think about variables as a name we assign to a particular object in Python

In [2]:
# assign a small array to a variable
a = np.array( [ [1,1,2], [3,5,8] ] )

When we run the cell, the variable and its value is stored. You can see the value in two ways:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## naming variables
We're going to use `snake_case` for naming variables. All lowercase, underscores to separate them

## variables and objects

**object**: object is a bundle of properties and actions about something specific.

Example:

- object: data frame
- properties: number of rows, names of columns, date created
- actions: selection a row, adding a column

Variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:

- The Sun = object
- sol = Spanish word for Sun = variable
- soleil = french for Sun = variable

In practice: we will use object and variable interchangeably. 

# Types

Each object in Python has a type.

type = what kind of object it is

Type is also the **class** of the object

We can see the type/class of an object by using the `type` function

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in `numpy`. We can check the type of an entry in the array by indexing:

In [6]:
print(a[0,0]) # indexing goes rows, columns
type(a[0,0])

1


numpy.int64

In [7]:
# how to access value 5 in the array
print(a[1,1])

5


# Functions

`print` is our first example of a Python function

A function:
- takes a set of **arguments** separated by commas
- takes those arguments to produce an **output**

argument is also called **parameter**

We can ask information about a function by executing `?` followed by function name

In [8]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


Contains:
- first line: function showing all of its arguments in ()
- short description of what the function does
- list of the arguments and a brief explanation of each

Different types of arguments inside the parentheses. there are two types:

- **non-optional**: arguments you need to specify for the function to do something
- **optional**: arguments pre-filled with a value, but we can override them. Optional arguments appear inside the parentheses as 

`optional argument = default_value`

In [2]:
print('changing the \ndefault end argument', end=':)')

changing the 
default end argument:)

## attributes and methods
an object in Python has attributes and methods

**attribute**: a property of an object, a piece of information about it
**method**: a procedure associated with an object, a function where the main parameter is the object

Acess an objects attributes and methods by adding a `.` at the end of the variable's name

`variable.variable_method()` or

`variable.variable_attribute`

Example:

Methods and attributes of NumPy arrays:

In [3]:
import numpy as np

In [6]:
# define a 3 x 3 array
var = np.array( [[1,2,3], [4,5,6], [7,8,9]] )
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# shape: attribute telling the number of elements in each dimension of the array
var.shape

(3, 3)

In [8]:
type(var.shape)

tuple

In [9]:
# ndim is an attribute holding the number of array dimensions
var.ndim

2

In [10]:
type(var.ndim)

int

Notice attributes can have many different datatypes.

Examples of methods

In [11]:
# min method for array, returns the minimum value in the array
var.min()

1

In [12]:
type(var.min)

builtin_function_or_method

# R and Python
R:
- doesn't use methods within an object
- functions are extrinsic to (outside) the objects they are acting on

Example: recreate getting the min value in an array

In R there'd be two separate items: the variable `var` and separate function `min` that gets `var` as a parameter:

```
# R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
min(var)
```

Using pipe operator in tidyverse is closer to the `.` in Python:

```
var <- array(c(1,4,7,2,5,8,3,6,9, dim=c(3,3))
var %>% min()
```

The pipe is passing `var` to `min()` as its first argument. It's essentially what the period does in Python. 